# Module for implementing structured ninja build system data.

class Ninja:
    """
    A class to structure ninja build data and generate ninja build files.

    See: https://ninja-build.org/manual.html
    """

    class Build:
        """
        A ninja build object, which is used to specify dependencies between files and
        what rule to apply to the explicit dependencies.
        """

        def __init__(self, rule: str, out: list, explicit_deps: list, implicit_deps: list, vars: dict):
            """
            Create a new Build instance.

            ### Parameters
            - `rule`: name of the rule to apply to the input files
            - `out`: list of files to generate from the applied rule
            - `explicit_deps`: list of files required and available in ${in}
            - `implicit_deps`: list of files required but unavailable in ${in}
            - `vars`: optional dictionary of bindings to shadow
            """
            self.rule = rule
            self.out = out
            self.explicit_deps = explicit_deps
            self.implicit_deps = implicit_deps
            self.vars = vars

    def __init__(self):
        """
        Create a new Ninja instance.
        """
        self.bindings = dict()
        self.rules = dict()
        self.builds = []
        pass

    def add_rule(self, name: str, command: str):
        """
        Adds a new rule identified as `name` that executes command `command`.
        """
        self.rules[name] = command

    def add_def_var(self, var: str, bind: str):
        """
        Adds a new default binding for `var` = `bind`.
        """
        self.bindings[var] = bind

    def add_build(self, rule: str, out: list, explicit_deps: list=[], implicit_deps: list=[], vars: dict=dict()):
        """
        Creates a new Build object and adds it to the build graph.
        """
        if isinstance(out, str):
            out = [out]
        if isinstance(explicit_deps, str):
            explicit_deps = [explicit_deps]
        if isinstance(implicit_deps, str):
            implicit_deps = [implicit_deps]
        self.builds += [Ninja.Build(rule, out, explicit_deps, implicit_deps, vars)]

    def __str__(self):
        """
        Serializes the data into a Ninja build file format.
        """
        data = ''
        data += '# This file was automatically @generated by another program.\n'
        data += '# It is not intended for manual editing.\n\n'

        def fmt_file_list(files: list):
            result = ' '
            for f in files:
                # escape spaces in file paths
                result += f.replace(' ', '$ ') + ' '
            return result[:-1]

        # add default bindings
        if len(self.bindings) > 0:
            data += '# Default variable expressions (bindings)\n' 
            sorted_vars = list(self.bindings.keys())
            sorted_vars.sort()
            for var in sorted_vars:
                data += var + ' = ' + self.bindings[var] + '\n'
            data += '\n'
        # add rules
        if len(self.rules) > 0:
            data += '# Rules\n'
            sorted_rules = list(self.rules.keys())
            sorted_rules.sort()
            for name in sorted_rules:
                data += 'rule ' + name + '\n  '
                data += self.rules[name] + '\n\n'
        # add builds
        if len(self.builds) > 0:
            data += '# Builds\n'
            build: Ninja.Build
            for build in self.builds:
                data += 'build ' + fmt_file_list(build.out) + ': ' + build.rule + ' ' + fmt_file_list(build.explicit_deps)
                if len(build.implicit_deps) > 0:
                    data += ' | ' + fmt_file_list(build.implicit_deps)
                data += '\n'
                if len(build.vars) > 0:
                    sorted_vars = list(build.vars.keys())
                    sorted_vars.sort()
                    for var in sorted_vars:
                        data += '  ' + var + ' = ' + build.vars[var] + '\n'
                data += '\n'
        return data
    
    def save(self, path: str='build.ninja'):
        """
        Write the Ninja build contents to the file at `path`.
        """
        with open(path, 'w') as fd:
            fd.write(str(self))